const { contextBridge, ipcRenderer } = require('electron');

// Veilige brug van IPC vanuit de renderer — geen directe Node.js-toegang
contextBridge.exposeInMainWorld('stig', {
  selectFile:       ()                                          => ipcRenderer.invoke('stig:select-file'),
  peekFile:         (filePath)                                  => ipcRenderer.invoke('stig:peek-file', filePath),
  importFile:       (filePath, platform, version, releaseDate, compareWithVersionId, useCaseId) => ipcRenderer.invoke('stig:import-file', filePath, platform, version, releaseDate, compareWithVersionId, useCaseId),
  getAllVersions:    ()                                          => ipcRenderer.invoke('stig:get-all-versions'),
  getRules:         (versionId)                                 => ipcRenderer.invoke('stig:get-rules', versionId),
  saveAnnotation:   (data)                                      => ipcRenderer.invoke('stig:save-annotation', data),
  getAnnotation:    (ruleId)                                    => ipcRenderer.invoke('stig:get-annotation', ruleId),
  getExpiringItems: (days)                                      => ipcRenderer.invoke('stig:get-expiring', days),
  getMappings:      (versionId)                                 => ipcRenderer.invoke('stig:get-mappings', versionId),
  exportCsv:        (versionId)                                 => ipcRenderer.invoke('stig:export-csv', versionId),
  exportJson:       ()                                          => ipcRenderer.invoke('stig:export-json'),
  saveFile:                  (defaultName, content) => ipcRenderer.invoke('stig:save-file', defaultName, content),
  getAnnotationsByVersion:   (versionId)                                => ipcRenderer.invoke('stig:get-annotations-by-version', versionId),
  getPlatforms:              ()                                     => ipcRenderer.invoke('stig:get-platforms'),
  downloadAndImport:         (url, platform, version, releaseDate, compareWithVersionId, useCaseId) => ipcRenderer.invoke('stig:download-and-import', url, platform, version, releaseDate, compareWithVersionId, useCaseId),
  getUseCases:               ()                  => ipcRenderer.invoke('stig:get-use-cases'),
  createUseCase:             (name)              => ipcRenderer.invoke('stig:create-use-case', name),
  renameUseCase:             (id, name)          => ipcRenderer.invoke('stig:rename-use-case', id, name),
  deleteUseCase:             (id)                => ipcRenderer.invoke('stig:delete-use-case', id),
  getVersionsByUseCase:      (id)                => ipcRenderer.invoke('stig:get-versions-by-use-case', id),
  getVersionStats:           (useCaseId)         => ipcRenderer.invoke('stig:get-version-stats', useCaseId),
  updateUseCaseSettings:     (id, settings)      => ipcRenderer.invoke('stig:update-use-case-settings', id, settings),
  onDownloadProgress:        (cb) => ipcRenderer.on('stig:download-progress', (_, pct) => cb(pct)),
  offDownloadProgress:       ()   => ipcRenderer.removeAllListeners('stig:download-progress'),
  deleteVersion:             (versionId)           => ipcRenderer.invoke('stig:delete-version', versionId),
  exportVersionJson:         (versionId)           => ipcRenderer.invoke('stig:export-version-json', versionId),
  importVersionJson:         ()                    => ipcRenderer.invoke('stig:import-version-json'),
  backupDatabase:            ()                    => ipcRenderer.invoke('stig:backup-database'),
  restoreDatabase:           ()                    => ipcRenderer.invoke('stig:restore-database'),
  getRule:                   (ruleId)              => ipcRenderer.invoke('stig:get-rule', ruleId),
  acceptMapping:             (oldRuleId, newRuleId) => ipcRenderer.invoke('stig:accept-mapping', oldRuleId, newRuleId),
  rejectMapping:             (newRuleId)            => ipcRenderer.invoke('stig:reject-mapping', newRuleId),
});
